//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.34014
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace vGamePad.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("vGamePad.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   {0} AST {1:00}:{2:00}  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AstClockString01 {
            get {
                return ResourceManager.GetString("AstClockString01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   朝 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AstClockString02 {
            get {
                return ResourceManager.GetString("AstClockString02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   夜 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AstClockString03 {
            get {
                return ResourceManager.GetString("AstClockString03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}まであと{1:00}分{2:00}秒 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AstClockString04 {
            get {
                return ResourceManager.GetString("AstClockString04", resourceCulture);
            }
        }
        
        /// <summary>
        ///    {0}  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AstClockString05 {
            get {
                return ResourceManager.GetString("AstClockString05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MM/dd HH:mm に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AstClockString06 {
            get {
                return ResourceManager.GetString("AstClockString06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   デフォルトレイアウトで起動します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ButtonLayoutString01 {
            get {
                return ResourceManager.GetString("ButtonLayoutString01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} 時間を表示する に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ClockString01 {
            get {
                return ResourceManager.GetString("ClockString01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} アストルティア時間 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ClockString02 {
            get {
                return ResourceManager.GetString("ClockString02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} PCの時間 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ClockString03 {
            get {
                return ResourceManager.GetString("ClockString03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} ボタンのみ表示 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfigButton01 {
            get {
                return ResourceManager.GetString("ConfigButton01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} 画面メモを使う に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfigButton02 {
            get {
                return ResourceManager.GetString("ConfigButton02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} バッテリー残量を表示 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfigButton03 {
            get {
                return ResourceManager.GetString("ConfigButton03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} ①-④ボタンの連射を使う に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfigButton04 {
            get {
                return ResourceManager.GetString("ConfigButton04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   vGamePadメッセージ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DialogTitle {
            get {
                return ResourceManager.GetString("DialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   強制的にvGamePadを終了します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ExceptionMessage001 {
            get {
                return ResourceManager.GetString("ExceptionMessage001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ご利用の環境にはタッチスクリーン機能がありません。
        ///vGamePadをご利用いただけません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ExceptionMessage002 {
            get {
                return ResourceManager.GetString("ExceptionMessage002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   vGamePad エラーメッセージ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ExceptionTitle {
            get {
                return ResourceManager.GetString("ExceptionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   vGamePadを終了してもよろしいですか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ExitApplication {
            get {
                return ResourceManager.GetString("ExitApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ボタンレイアウト作成モードに移行します。
        ///よろしいですか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LayoutSelectMessage {
            get {
                return ResourceManager.GetString("LayoutSelectMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ボタンレイアウトの作成 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LayoutSelectTitle {
            get {
                return ResourceManager.GetString("LayoutSelectTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   レイアウト1 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LayoutSettingLayout1 {
            get {
                return ResourceManager.GetString("LayoutSettingLayout1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   レイアウト2 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LayoutSettingLayout2 {
            get {
                return ResourceManager.GetString("LayoutSettingLayout2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   デフォルト レイアウト に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LayoutSettingLayoutDefault {
            get {
                return ResourceManager.GetString("LayoutSettingLayoutDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   レイアウトの編集を終了してもよろしいですか？
        ///編集内容は破棄されます。注意してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LayoutWindowCloseMessage {
            get {
                return ResourceManager.GetString("LayoutWindowCloseMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   vGamePad ボタンレイアウト - 終了 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LayoutWindowCloseTitle {
            get {
                return ResourceManager.GetString("LayoutWindowCloseTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ロードするボタンレイアウトを選択してください。
        ///編集中のレイアウトは破棄されるので注意してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LayoutWindowLoadMessage {
            get {
                return ResourceManager.GetString("LayoutWindowLoadMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   vGamePad ボタンレイアウト - 読込 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LayoutWindowLoadTitle {
            get {
                return ResourceManager.GetString("LayoutWindowLoadTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   レイアウトを初期状態に戻します。
        ///編集内容は破棄されます。注意してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LayoutWindowResetMessage {
            get {
                return ResourceManager.GetString("LayoutWindowResetMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   vGamePad ボタンレイアウト - リセット に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LayoutWindowResetTitle {
            get {
                return ResourceManager.GetString("LayoutWindowResetTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ボタンレイアウトの保存場所を選択してください。
        ///すでに存在する場合は上書きされるので注意してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LayoutWindowSaveMessage {
            get {
                return ResourceManager.GetString("LayoutWindowSaveMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   vGamePad ボタンレイアウト - 保存 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LayoutWindowSaveTitle {
            get {
                return ResourceManager.GetString("LayoutWindowSaveTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   充電してください に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PowerStatusString01 {
            get {
                return ResourceManager.GetString("PowerStatusString01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   初期化中... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PowerStatusString02 {
            get {
                return ResourceManager.GetString("PowerStatusString02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   計算中... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PowerStatusString03 {
            get {
                return ResourceManager.GetString("PowerStatusString03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   残りプレイ {0:00}時間{1:00}分 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PowerStatusString04 {
            get {
                return ResourceManager.GetString("PowerStatusString04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   バッテリーがありません に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PowerStatusString05 {
            get {
                return ResourceManager.GetString("PowerStatusString05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ??? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PowerStatusString06 {
            get {
                return ResourceManager.GetString("PowerStatusString06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0,3} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PowerStatusString07 {
            get {
                return ResourceManager.GetString("PowerStatusString07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   充電中 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PowerStatusString08 {
            get {
                return ResourceManager.GetString("PowerStatusString08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   AC電源 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PowerStatusString09 {
            get {
                return ResourceManager.GetString("PowerStatusString09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} {1}%:{2} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PowerStatusString10 {
            get {
                return ResourceManager.GetString("PowerStatusString10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DQXGame に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ProcessName {
            get {
                return ResourceManager.GetString("ProcessName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System.IO.MemoryStream に類似した型 System.IO.UnmanagedMemoryStream のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Sound01 {
            get {
                return ResourceManager.GetStream("Sound01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   %ProgramFiles%\Common Files\microsoft shared\ink\TabTip.exe に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TabTip {
            get {
                return ResourceManager.GetString("TabTip", resourceCulture);
            }
        }
    }
}
