//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.34014
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeviceControl.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DeviceControl.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   vJoyのボタン数設定が12ではありません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string VJOY_BUTTON_NUMBER_FATAL {
            get {
                return ResourceManager.GetString("VJOY_BUTTON_NUMBER_FATAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   vJoyがインストールされていない、または、デバイスが無効です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string VJOY_ENABLE {
            get {
                return ResourceManager.GetString("VJOY_ENABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   POV(十字キー)の設定がない、または、正しく設定されていません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string VJOY_POV_FATAL {
            get {
                return ResourceManager.GetString("VJOY_POV_FATAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   すでに他プログラムがvJoyを使用しています。他のプログラムを終了してから再度起動してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string VJOY_STAT_OWN {
            get {
                return ResourceManager.GetString("VJOY_STAT_OWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アナログスティック(左)が正しく設定されていません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string VJOY_STICK_LEFT_FATAL {
            get {
                return ResourceManager.GetString("VJOY_STICK_LEFT_FATAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アナログスティック(右)が正しく設定されていません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string VJOY_STICK_RIGHT_FATAL {
            get {
                return ResourceManager.GetString("VJOY_STICK_RIGHT_FATAL", resourceCulture);
            }
        }
    }
}
